# Generated by Django 5.2 on 2025-04-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='course',
            field=models.CharField(choices=[('btech', 'B.Tech'), ('bba', 'BBA'), ('bsc', 'B.Sc'), ('ba', 'BA'), ('bcom', 'B.Com'), ('mba', 'MBA'), ('msc', 'M.Sc'), ('phd', 'Ph.D')], max_length=10),
        ),
    ]
